#!/bin/bash
# "Things To Do!" script for a fresh Fedora Workstation installation
#
# Generated by NATTD ver. 26.09 / F45 / 200+ Stars Edition
# Generation date: 2026-10-07 16:57
# Output mode: Quiet
#
#   - Set Hostname
#   - Configure DNF
#   - Enable DNF Autoupdate
#   - Replace Fedora Flatpak Repo with Flathub
#   - Update Firmware
#   - RPM Fusion Repositories
#   - Multimedia Codecs
#   - AMD Codecs
#   - rsync
#   - fastfetch
#   - unzip
#   - unrar
#   - git
#   - wget
#   - curl
#   - gnome-tweaks
#   - syncthing
#   - Brave (DNF)
#   - Discord (DNF)
#   - Bitwarden
#   - Steam (DNF)
#   - Lutris (DNF)
#   - Heroic Games Launcher
#   - Prism Launcher
#   - Proton VPN
#   - Custom user-defined commands



# Check if the script is run with sudo
if [ "$EUID" -ne 0 ]; then
    echo "Please run this script with sudo"
    exit 1
fi

# Funtion to echo colored text
color_echo() {
    local color="$1"
    local text="$2"
    case "$color" in
        "red")     echo -e "\033[0;31m$text\033[0m" ;;
        "green")   echo -e "\033[0;32m$text\033[0m" ;;
        "yellow")  echo -e "\033[1;33m$text\033[0m" ;;
        "blue")    echo -e "\033[0;34m$text\033[0m" ;;
        *)         echo "$text" ;;
    esac
}

# Set variables
ACTUAL_USER=$SUDO_USER
ACTUAL_HOME=$(eval echo ~$SUDO_USER)
LOG_FILE="/var/log/fedora_things_to_do.log"
INITIAL_DIR=$(pwd)

# Function to generate timestamps
get_timestamp() {
    date +"%Y-%m-%d %H:%M:%S"
}

# Function to log messages
log_message() {
    local message="$1"
    echo "$(get_timestamp) - $message" | tee -a "$LOG_FILE"
}

# Function to handle errors
handle_error() {
    local exit_code=$?
    local message="$1"
    if [ $exit_code -ne 0 ]; then
        color_echo "red" "ERROR: $message"
        exit $exit_code
    fi
}

# Failure tracking: every failing command increments the counter and is
# logged, but the script keeps going - a partial setup is still better
# than stopping halfway through.
FAILURES=0
log_message "=== NATTD run started ==="
trap 'FAILURES=$((FAILURES+1)); log_message "FAILED command (exit $?) at line $LINENO"' ERR

# Function to prompt for reboot
prompt_reboot() {
    sudo -u $ACTUAL_USER bash -c 'read -p "It is time to reboot the machine. Would you like to do it now? (y/n): " choice; [[ $choice == [yY] ]]'
    if [ $? -eq 0 ]; then
        color_echo "green" "Rebooting..."
        reboot
    else
        color_echo "red" "Reboot canceled."
    fi
}

# Function to backup configuration files
backup_file() {
    local file="$1"
    if [ -f "$file" ]; then
        cp "$file" "$file.bak"
        handle_error "Failed to backup $file"
        color_echo "green" "Backed up $file"
    fi
}

echo "";
echo "╔═════════════════════════════════════════════════════════════════════════════╗";
echo "║                                                                             ║";
echo "║   ░█▀▀░█▀▀░█▀▄░█▀█░█▀▄░█▀█░░░█░█░█▀█░█▀▄░█░█░█▀▀░▀█▀░█▀█░▀█▀░▀█▀░█▀█░█▀█░   ║";
echo "║   ░█▀▀░█▀▀░█░█░█░█░█▀▄░█▀█░░░█▄█░█░█░█▀▄░█▀▄░▀▀█░░█░░█▀█░░█░░░█░░█░█░█░█░   ║";
echo "║   ░▀░░░▀▀▀░▀▀░░▀▀▀░▀░▀░▀░▀░░░▀░▀░▀▀▀░▀░▀░▀░▀░▀▀▀░░▀░░▀░▀░░▀░░▀▀▀░▀▀▀░▀░▀░   ║";
echo "║   ░░░░░░░░░░░░▀█▀░█░█░▀█▀░█▀█░█▀▀░█▀▀░░░▀█▀░█▀█░░░█▀▄░█▀█░█░░░░░░░░░░░░░░   ║";
echo "║   ░░░░░░░░░░░░░█░░█▀█░░█░░█░█░█░█░▀▀█░░░░█░░█░█░░░█░█░█░█░▀░░░░░░░░░░░░░░   ║";
echo "║   ░░░░░░░░░░░░░▀░░▀░▀░▀▀▀░▀░▀░▀▀▀░▀▀▀░░░░▀░░▀▀▀░░░▀▀░░▀▀▀░▀░░░░░░░░░░░░░░   ║";
echo "║                                                                             ║";
echo "╚═════════════════════════════════════════════════════════════════════════════╝";
echo "";
echo "This script automates \"Things To Do!\" steps after a fresh Fedora Workstation installation"
echo "ver. 26.09 / F45 / 200+ Stars Edition"
echo ""
echo "Don't run this script if you didn't build it yourself or don't know what it does."
echo ""
read -p "Press Enter to continue or CTRL+C to cancel..."

# System Upgrade
color_echo "blue" "Performing system upgrade... This may take a while..."
dnf upgrade -y > /dev/null 2>&1


# System Configuration
# Set the system hostname to uniquely identify the machine on the network
color_echo "yellow" "Setting hostname..."
hostnamectl set-hostname noah > /dev/null 2>&1

# Optimize DNF package manager for faster downloads and efficient updates
color_echo "yellow" "Configuring DNF Package Manager..."
backup_file "/etc/dnf/dnf.conf" > /dev/null 2>&1
dnf -y install dnf-plugins-core > /dev/null 2>&1
# Max Parallel Downloads
echo "max_parallel_downloads=10" | tee -a /etc/dnf/dnf.conf > /dev/null
# Select Fastest Mirror
echo "fastestmirror=True" | tee -a /etc/dnf/dnf.conf > /dev/null
# Default Yes
echo "defaultyes=True" | tee -a /etc/dnf/dnf.conf > /dev/null

# Enable and configure automatic system updates to enhance security and stability
color_echo "yellow" "Enabling DNF autoupdate..."
dnf install dnf-automatic -y > /dev/null 2>&1
sed -i 's/apply_updates = no/apply_updates = yes/' /etc/dnf/automatic.conf > /dev/null 2>&1
systemctl enable --now dnf-automatic.timer > /dev/null 2>&1

# Replace Fedora Flatpak Repo with Flathub for better package management and apps stability
color_echo "yellow" "Replacing Fedora Flatpak Repo with Flathub..."
dnf install -y flatpak > /dev/null 2>&1
flatpak remote-delete fedora --force || true > /dev/null 2>&1
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo > /dev/null 2>&1
sudo flatpak repair > /dev/null 2>&1
flatpak update > /dev/null 2>&1

# Check and apply firmware updates to improve hardware compatibility and performance
color_echo "yellow" "Checking for firmware updates..."
fwupdmgr refresh --force > /dev/null 2>&1
fwupdmgr get-updates > /dev/null 2>&1
fwupdmgr update -y > /dev/null 2>&1

# Enable RPM Fusion repositories to access additional software packages and codecs
color_echo "yellow" "Enabling RPM Fusion repositories..."
dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm > /dev/null 2>&1
dnf install -y https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm > /dev/null 2>&1
dnf group install core -y > /dev/null 2>&1

# Install multimedia codecs to enhance multimedia capabilities
color_echo "yellow" "Installing multimedia codecs..."
dnf swap ffmpeg-free ffmpeg --allowerasing -y > /dev/null 2>&1
dnf group install multimedia --setopt="install_weak_deps=False" --exclude=PackageKit-gstreamer-plugin -y > /dev/null 2>&1
dnf group install sound-and-video -y > /dev/null 2>&1

# Install Hardware Accelerated Codecs for AMD GPUs. This improves video playback and encoding performance on systems with AMD graphics.
color_echo "yellow" "Installing AMD Hardware Accelerated Codecs..."
color_echo "blue" "Note: on some AMD GPUs the freeworld VA-API drivers can cause a performance regression in games. If you notice lower FPS afterwards, revert with: sudo dnf swap mesa-va-drivers-freeworld mesa-va-drivers -y && sudo dnf swap mesa-vdpau-drivers-freeworld mesa-vdpau-drivers -y"
dnf swap mesa-va-drivers mesa-va-drivers-freeworld -y > /dev/null 2>&1
dnf swap mesa-vdpau-drivers mesa-vdpau-drivers-freeworld -y > /dev/null 2>&1


# App Installation
# Install essential applications
color_echo "yellow" "Installing essential applications..."
dnf install -y rsync fastfetch unzip unrar git wget curl gnome-tweaks syncthing > /dev/null 2>&1
color_echo "green" "Essential applications installed successfully."

# Install Internet & Communication applications
color_echo "yellow" "Installing Brave..."
dnf install -y dnf-plugins-core > /dev/null 2>&1
if command -v dnf4 &>/dev/null; then
  dnf4 config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo > /dev/null 2>&1
else
  dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo > /dev/null 2>&1
fi
rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc > /dev/null 2>&1
dnf install -y brave-browser > /dev/null 2>&1
color_echo "green" "Brave installed successfully."
color_echo "yellow" "Installing Discord..."
dnf install -y discord > /dev/null 2>&1
color_echo "green" "Discord installed successfully."

# Install Office Productivity applications
color_echo "yellow" "Installing Bitwarden..."
flatpak install -y flathub com.bitwarden.desktop > /dev/null 2>&1
color_echo "green" "Bitwarden installed successfully."

# Install Gaming & Emulation applications
color_echo "yellow" "Installing Steam..."
dnf install -y steam > /dev/null 2>&1
color_echo "green" "Steam installed successfully."
color_echo "yellow" "Installing Lutris..."
dnf install -y lutris > /dev/null 2>&1
color_echo "green" "Lutris installed successfully."
color_echo "yellow" "Installing Heroic Games Launcher..."
flatpak install -y flathub com.heroicgameslauncher.hgl > /dev/null 2>&1
color_echo "green" "Heroic Games Launcher installed successfully."
color_echo "yellow" "Installing Prism Launcher..."
flatpak install -y flathub org.prismlauncher.PrismLauncher > /dev/null 2>&1
color_echo "green" "Prism Launcher installed successfully."

# Install Remote Networking applications
color_echo "yellow" "Installing Proton VPN..."
flatpak install -y flathub com.protonvpn.www > /dev/null 2>&1
color_echo "green" "Proton VPN installed successfully."


# Customization


# Custom user-defined commands
# Custom user-defined commands
echo "Created with ❤️ for Open Source"


# Before finishing, ensure we're in a safe directory
cd /tmp || cd $ACTUAL_HOME || cd /

# Finish - report the actual outcome instead of pretending everything worked
log_message "=== NATTD run finished with $FAILURES failed command(s) ==="
if [ "$FAILURES" -eq 0 ]; then
    color_echo "green" "All steps completed successfully. Enjoy!"
else
    color_echo "yellow" "All steps attempted, but $FAILURES command(s) reported an error."
    color_echo "yellow" "Check $LOG_FILE for details (grep for 'FAILED'), then re-run the script -"
    color_echo "yellow" "it is safe to run again, already-installed parts will be skipped or upgraded."
fi
echo "";
echo "╔═════════════════════════════════════════════════════════════════════════╗";
echo "║                                                                         ║";
echo "║   ░█░█░█▀▀░█░░░█▀▀░█▀█░█▄█░█▀▀░░░▀█▀░█▀█░░░█▀▀░█▀▀░█▀▄░█▀█░█▀▄░█▀█░█░   ║";
echo "║   ░█▄█░█▀▀░█░░░█░░░█░█░█░█░█▀▀░░░░█░░█░█░░░█▀▀░█▀▀░█░█░█░█░█▀▄░█▀█░▀░   ║";
echo "║   ░▀░▀░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀░░░░▀░░▀▀▀░░░▀░░░▀▀▀░▀▀░░▀▀▀░▀░▀░▀░▀░▀░   ║";
echo "║                                                                         ║";
echo "╚═════════════════════════════════════════════════════════════════════════╝";
echo "";

# Prompt for reboot
prompt_reboot
